import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';
import fs from 'fs';
import path from 'path';

// Plugin: generate firebase-messaging-sw.js with env vars baked in at build time
function fcmServiceWorker(env) {
  return {
    name: 'fcm-sw-generator',
    buildStart() {
      const swContent = `// Auto-generated by vite.config.js — do not edit manually
importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-messaging-compat.js');

firebase.initializeApp({
  apiKey:            "${env.VITE_FIREBASE_API_KEY || ''}",
  authDomain:        "${env.VITE_FIREBASE_AUTH_DOMAIN || ''}",
  projectId:         "${env.VITE_FIREBASE_PROJECT_ID || ''}",
  storageBucket:     "${env.VITE_FIREBASE_STORAGE_BUCKET || ''}",
  messagingSenderId: "${env.VITE_FIREBASE_MESSAGING_SENDER_ID || ''}",
  appId:             "${env.VITE_FIREBASE_APP_ID || ''}",
});

const messaging = firebase.messaging();

// Handle background messages (app is closed or in background)
// NOTE: When FCM payload has a 'notification' field, Chrome may show it automatically.
// onBackgroundMessage handles the case where we need to construct the display ourselves.
messaging.onBackgroundMessage(payload => {
  // Support both notification field and data-only payloads
  const title = (payload.notification && payload.notification.title)
    || (payload.data && payload.data.title) || '';
  const body  = (payload.notification && payload.notification.body)
    || (payload.data && payload.data.body)  || '';
  const data  = payload.data || {};
  if (!title) return;
  self.registration.showNotification(title, {
    body,
    icon:  '/favicon.png',
    badge: '/favicon.png',
    tag:   data.tag || 'gpp-notification',
    requireInteraction: false,
    data:  { url: data.url || '/' },
  });
});

// On notification click — open/focus the app at the relevant URL
self.addEventListener('notificationclick', event => {
  event.notification.close();
  const url = event.notification.data?.url || '/';
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(list => {
      const existing = list.find(c => c.url.includes(self.location.origin));
      if (existing) { existing.focus(); existing.navigate(url); }
      else clients.openWindow(url);
    })
  );
});
`;
      const outPath = path.resolve('./public/firebase-messaging-sw.js');
      fs.writeFileSync(outPath, swContent);
      console.log('[fcm-sw] Generated public/firebase-messaging-sw.js');
    },
  };
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');
  return {
    plugins: [react(), fcmServiceWorker(env)],
  };
});
